server:
  port: 8787

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csm_regional
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  resources:
    chain:
      enabled: true

security:
  basic:
    enabled: false